apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: eshop-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          env:
            - name: MP_MAX_MESSAGES
              value: "5000"
            - name: MP_DATABASE
              value: "/data/mailpit.db"
            - name: MP_SMTP_AUTH_ACCEPT_ANY
              value: "1"
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: "1"
          ports:
            - containerPort: 8025
              name: ui
            - containerPort: 1025
              name: smtp
          livenessProbe:
            httpGet:
              path: /livez
              port: 8025
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8025
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailpit-pvc
