apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: eshop-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      serviceAccountName: sa-observability
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          args:
            - "--query.ui-config=/etc/jaeger/jaeger-ui.json"
            - "--collector.otlp.enabled=true"
            - "--prometheus.server-url=http://prometheus:9090"
            - "--prometheus.query.support-spanmetrics-connector=true"
          env:
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: PROMETHEUS_QUERY_NORMALIZE_CALLS
              value: "true"
            - name: PROMETHEUS_QUERY_NORMALIZE_DURATION
              value: "true"
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 14268
              name: collector-http
            - containerPort: 14269
              name: admin
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 6831
              name: agent-udp
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: jaeger-ui-config
              mountPath: /etc/jaeger
      volumes:
        - name: jaeger-ui-config
          configMap:
            name: jaeger-ui-config
