apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: eshop-microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: basket-db-secret
  namespace: eshop-microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-db-secret
  namespace: eshop-microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-command-db-secret
  namespace: eshop-microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-query-db-secret
  namespace: eshop-microservices
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
