apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: eshop-microservices
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: eshop-microservices
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
