global using Order.Command.Application.Dtos;
global using Order.Command.Application.Data;
global using Order.Command.Domain.Models;
global using Order.Command.Domain.Models.ValueObjects;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Order.Command.Domain.Events;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
global using Serilog.Context;
global using ILogger = Serilog.ILogger;
global using eshop.Shared.Logger;