apiVersion: v1
kind: Service
metadata:
  name: order-command-db-headless
  namespace: eshop-microservices
spec:
  clusterIP: None
  selector:
    app: order-command-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: order-command-db
  namespace: eshop-microservices
spec:
  selector:
    app: order-command-db
  ports:
    - port: 5432
      targetPort: 5432
