apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: eshop-microservices
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
