apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-config
  namespace: eshop-microservices
data:
  jaeger-ui.json: |
    {
      "monitor": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      }
    }
  sampling_strategies.json: |
    {
      "default_strategy": {
        "type": "probabilistic",
        "param": 1
      }
    }
